程序    =   { ( 版本声明 | 包声明 | 导入声明 | 服务声明 | 消息声明 | 枚举声明 ) ";" }  ;


版本声明      =   "syntax" "=" CONST-STRING                ;
包声明        =   "package"   引用声明                      ;
导入声明      =   "import"    CONST-STRING                 ;
服务声明      =   "service"   名字 "{" 服务字段列表 "}"       ;
消息声明      =   "message"   名字 "{" 消息字段列表 "}"       ;
枚举声明      =   "enum"      名字 "{" 枚举字段列表 "}"       ;



服务字段列表    =   { ( 方法声明 | 消息声明 | 枚举声明 | 导入声明 )            ";" }    ;
消息字段列表    =   { ( 选项声明 | 字段声明 | 保留声明 | 枚举声明 | 消息声明 )  ";" }    ;
枚举字段列表    =   { ( 枚举项声明 | 保留声明                               ";" }    ;


引用声明      =     名字    {"."   名字 } ";"  ;

 